In [1]:
# WAYS TO CREATE AN ARRAY
# array , arange , linspace
# zeros , ones , zeros_like , ones_like , eye , identity

In [2]:
import numpy as np

In [4]:
arr = np.zeros((3,3))

In [6]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr = np.zeros((3,3,),dtype=int)

In [9]:
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
arr = np.ones((3,3))

In [11]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr = np.ones((2,3),dtype=int)

In [15]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
myarr = np.array([ [1,2,3,4],[5,6,7,8] ])

In [19]:
myarr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr = np.zeros_like(myarr)

In [23]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
arr = np.ones_like(myarr)

In [25]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
arr = np.eye(4)

In [27]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
arr = np.eye(4,dtype=int)

In [32]:
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [35]:
arr = np.eye(3,4)

In [36]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [37]:
arr = np.eye(3,4,dtype=int)

In [38]:
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [44]:
# Only 1 Argument for shape
arr = np.identity(4)

In [45]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
arr = np.identity(3,dtype=int)

In [43]:
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [68]:
# random functions 
# random (values between from 0 to 1) , randint
# random (0,1]
# randint (start,stop)

In [69]:
arr = np.random.random(5)

In [70]:
arr

array([0.58725125, 0.84969213, 0.9588525 , 0.79966148, 0.99160413])

In [95]:
# randint
arr = np.random.randint(1,10,3)

In [96]:
arr

array([3, 8, 5], dtype=int32)

In [152]:
arr = np.random.randint(1,10,(3,3))

In [153]:
arr

array([[7, 7, 7],
       [6, 5, 1],
       [6, 1, 9]], dtype=int32)

In [154]:
import random

In [155]:
print(random.randint(1,4))

2


In [163]:
# full
arr = np.full((3,3),8)

In [164]:
arr

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [169]:
# diag
arr = np.diag((2,4,5,7,9,3))

In [170]:
arr

array([[2, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 9, 0],
       [0, 0, 0, 0, 0, 3]])

In [171]:
# How do you create a NumPy array from a Python list?
li = [2,4,6,7,9]
arr = np.array(li)
arr , type(arr)

(array([2, 4, 6, 7, 9]), numpy.ndarray)

In [175]:
#What is the difference between np.array() and np.asarray()?
arr2 = np.asarray(arr)

In [176]:
arr2

array([2, 4, 6, 7, 9])

In [177]:
arr

array([2, 4, 6, 7, 9])

In [178]:
type(arr) , arr.shape , arr.size

(numpy.ndarray, (5,), 5)

In [179]:
arr = np.array([[2,3,5],[2,4,6]])

In [180]:
arr

array([[2, 3, 5],
       [2, 4, 6]])

In [181]:
type(arr) , arr.shape , arr.size

(numpy.ndarray, (2, 3), 6)

In [182]:
arr

array([[2, 3, 5],
       [2, 4, 6]])

In [183]:
arr.shape

(2, 3)

In [188]:
arr.reshape(3,2)

array([[2, 3],
       [5, 2],
       [4, 6]])

In [191]:
# How do you generate a random 5×5 matrix using NumPy?
arr = np.random.randint(1,10,(5,5))

In [192]:
arr

array([[5, 8, 7, 7, 6],
       [6, 9, 9, 6, 6],
       [6, 9, 2, 9, 1],
       [4, 9, 2, 6, 7],
       [3, 4, 1, 2, 1]], dtype=int32)

In [198]:
# How do you filter an array to get all values greater than a given number?
num = 5
arr = np.array([2,4,7,8,7,5,4,6,8,0,8,5,3])
for a in arr:
    if(a>num):
        print(a)

7
8
7
6
8
8


In [199]:
li

[np.int64(7), np.int64(8), np.int64(7), np.int64(6), np.int64(8), np.int64(8)]