In [1]:
# Numpy 2D Arrays
import numpy as np

In [10]:
mat = np.array([ [1,2,3],[4,5,6],[7,8,9] ])

In [11]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
mat.shape

(3, 3)

In [13]:
print("Rows : ",mat.shape[0])
print("Columns : ",mat.shape[1])

Rows :  3
Columns :  3


In [14]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
mat[1]

array([4, 5, 6])

In [17]:
mat[0][1]

np.int64(2)

In [18]:
mat[2][2]

np.int64(9)

In [24]:
for i in range(0,3):
    for j in range(0,3):
        print(mat[i][j],end="  ")
    print()

1  2  3  
4  5  6  
7  8  9  


In [38]:
mat1 = np.array([ [1,2,3],[4,5,6],[7,8,9],[2,5,7] ])
mat2 = np.array([ [2,5,8],[2,6,8],[8,5,2],[6,3,2] ])
mat1 , mat2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 5, 7]]),
 array([[2, 5, 8],
        [2, 6, 8],
        [8, 5, 2],
        [6, 3, 2]]))

In [44]:
# Addition of two Matrix
if(mat1.shape[0]==mat2.shape[0] and mat1.shape[1]==mat2.shape[1]):
    for i in range(0,mat1.shape[0]):
        for j in range(0,mat1.shape[1]):
            print(mat1[i][j]+mat2[i][j],end=" ")
        print()
else:
    print("Addition Not Possible")

3 7 11 
6 11 14 
15 13 11 
8 8 9 


In [45]:
# Transpose Of A Matrix
mat3 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
mat3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
for i in range(0,mat3.shape[0]):
    for j in range(0,mat3.shape[1]):
        print(mat3[j][i],end="   ")
    print()

1   4   7   
2   5   8   
3   6   9   


In [51]:
mat1 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
mat2 = np.array([ [2,5,8],[2,6,8],[8,5,2] ])
mat3 = np.zeros_like(mat1)
mat1 , mat2 , mat3

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[2, 5, 8],
        [2, 6, 8],
        [8, 5, 2]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

In [54]:
for i in range(0,3):
    for j in range(0,3):
        val = 0
        for k in range(0,3):
            val = val + mat1[i][k]*mat2[k][j]
        mat3[i][j] = val

In [55]:
mat3

array([[ 30,  32,  30],
       [ 66,  80,  84],
       [102, 128, 138]])